"""
Apache Airflow DAG generated automatically by AI DataGov ETL Studio.
Pipeline Name: {{ $pipeline_name }}
Generated At: {{ $generated_at }}
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
import logging

# Default arguments for the DAG
default_args = {
    'owner': 'ai_datagov',
    'depends_on_past': False,
    'start_date': datetime({{ date('Y, n, j') }}),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# ------------------------------------------------------------------------
# TASK CALLABLE FUNCTIONS
# ------------------------------------------------------------------------

@foreach($tasks as $task)
def {{ $task['function'] }}(**kwargs):
    """
    {{ $task['type'] }} Task: {{ $task['name'] }}
    {{ $task['desc'] }}
    """
    logging.info("Memulai task: {{ $task['name'] }}")
@if($task['type'] === 'Extract')
    logging.info("Membaca data dari tabel sumber: {{ $task['meta']['table'] }}")
    # TODO: Ambil koneksi database dan query data
    # query = "SELECT * FROM {{ $task['meta']['table'] }}"
    return {"status": "extracted", "table": "{{ $task['meta']['table'] }}"}
@elseif($task['type'] === 'Transform')
    ti = kwargs['ti']
    # Tarik status dari task hulu (upstream)
    input_data = ti.xcom_pull(task_ids='{{ $task['parent_id'] }}')
    logging.info("Menerapkan transformasi...")
@if(!empty($task['meta']['mappings']))
    # Mapping Kolom yang Terdeteksi:
@foreach($task['meta']['mappings'] as $map)
    # - {{ $map['source'] }} -> {{ $map['target'] }}
@endforeach
@endif
    return {"status": "transformed", "step": "{{ $task['name'] }}"}
@elseif($task['type'] === 'Load')
    ti = kwargs['ti']
    input_data = ti.xcom_pull(task_ids='{{ $task['parent_id'] }}')
    logging.info("Memuat data hasil transformasi ke tabel tujuan: {{ $task['meta']['table'] }}")
    # TODO: Hubungkan ke DWH dan jalankan bulk insert
    return {"status": "loaded", "table": "{{ $task['meta']['table'] }}"}
@endif


@endforeach
# ------------------------------------------------------------------------
# DAG DEFINITION
# ------------------------------------------------------------------------

with DAG(
    dag_id='{{ $dag_id }}',
    default_args=default_args,
    description='ETL pipeline {{ $pipeline_name }} generated by AI DataGov',
    schedule_interval={!! $schedule_interval !!},
    catchup=False,
    tags=['ai_datagov', 'etl_studio'],
) as dag:

    # Define PythonOperators for each task
@foreach($tasks as $task)
    {{ $task['id'] }} = PythonOperator(
        task_id='{{ $task['id'] }}',
        python_callable={{ $task['function'] }},
    )

@endforeach
    # Define task dependencies flow
@foreach($dependencies as $dep)
    {!! $dep !!}
@endforeach
